# Generated by Django 6.0.8 on 2026-09-02 21:10

import django.db.models.deletion
import dlux.models.asset_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0018_managed_asset_namespace'),
        ('public_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccataloglisting',
            name='image_override_asset',
            field=dlux.models.asset_field.ManagedAssetField(blank=True, kind='image', null=True, on_delete=django.db.models.deletion.PROTECT, reads=['catalog.product', 'catalog.service'], to='dlux.managedasset', verbose_name='Public image'),
        ),
    ]
