# Generated by Django 6.0.8 on 2026-09-02 21:08

import django.db.models.deletion
import dlux.models.asset_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariant_purchaseinvoiceline_variant_and_more'),
        ('dlux', '0018_managed_asset_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_asset',
            field=dlux.models.asset_field.ManagedAssetField(blank=True, kind='image', null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.managedasset', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_asset',
            field=dlux.models.asset_field.ManagedAssetField(blank=True, kind='image', null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.managedasset', verbose_name='Image'),
        ),
    ]
