# Generated by Django 6.0.8 on 2026-10-01 02:35

import finance.currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_pos_phase1'),
    ]

    operations = [
        # Existing rows were all priced in USD; new rows take the store's pricing currency.
        migrations.AddField(
            model_name='purchaseinvoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default=finance.currency.pricing_currency, max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Exchange Rate (LYD per unit)'),
        ),
    ]
