# Generated by Django 6.0.8 on 2026-10-03 13:06

import finance.currency
from django.db import migrations, models


def backfill_currency(apps, schema_editor):
    Settings = apps.get_model("dlux", "SystemSettings")
    extra = Settings.objects.using(schema_editor.connection.alias).values_list("extra_config", flat=True).first() or {}
    extra = extra if isinstance(extra, dict) else {}
    bag = extra.get("app")
    bag = bag if isinstance(bag, dict) else {}
    config = bag.get("switch_pos.pricing")
    config = config if isinstance(config, dict) else {}
    currency = str(config.get("currency") or "USD").upper()
    if currency not in ("USD", "EUR"):
        currency = "USD"
    apps.get_model("catalog", "Product").objects.using(schema_editor.connection.alias).all().update(currency=currency)
    # Remove only the old generated currency labels; preserve custom wording.
    legacy_labels = {
        "Import Cost (USD)", "Import Cost (EUR)", "Selling Price (USD)", "Selling Price (EUR)",
        "تكلفة الاستيراد (دولار)", "تكلفة الاستيراد (يورو)", "سعر البيع (دولار)", "سعر البيع (يورو)",
    }
    keys = {"label_product_cost_usd", "label_product_price_usd",
            "label_purchaseinvoiceline_cost_usd", "label_purchaseinvoiceline_price_usd"}
    for settings in Settings.objects.using(schema_editor.connection.alias).all():
        language = settings.language_config
        if not isinstance(language, dict):
            continue
        overrides = language.get("translations_override")
        if not isinstance(overrides, dict):
            continue
        changed = False
        for bucket in overrides.values():
            if not isinstance(bucket, dict):
                continue
            for key in keys:
                if isinstance(bucket.get(key), str) and bucket[key] in legacy_labels:
                    bucket.pop(key)
                    changed = True
        if changed:
            language["translations_override"] = overrides
            Settings.objects.using(schema_editor.connection.alias).filter(pk=settings.pk).update(language_config=language)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alias',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local alias'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=3, verbose_name='Pricing currency'),
        ),
        migrations.RunPython(backfill_currency, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product', name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default=finance.currency.pricing_currency, max_length=3, verbose_name='Pricing currency'),
        ),
    ]
