# Generated by Django 6.0.8 on 2026-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_category_parent_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Service category'),
        ),
    ]
