# Generated by Django 6.0.8 on 2026-09-22 21:25

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0007_product_service_image_assets"),
        ("dlux", "0020_update_run_applying_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleMake",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Deleted At")),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("deleted_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Deleted By")),
                ("scope", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dlux.scope", verbose_name="Scope")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Updated By")),
            ],
            options={
                "verbose_name": "Vehicle Make",
                "verbose_name_plural": "Vehicle Makes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Deleted At")),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("deleted_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Deleted By")),
                ("make", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="vehicle_models", to="automotive.vehiclemake", verbose_name="Make")),
                ("scope", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dlux.scope", verbose_name="Scope")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Updated By")),
            ],
            options={
                "verbose_name": "Vehicle Model",
                "verbose_name_plural": "Vehicle Models",
                "ordering": ["make__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleGeneration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Deleted At")),
                ("name", models.CharField(max_length=120, verbose_name="Generation")),
                ("chassis_code", models.CharField(blank=True, max_length=80, verbose_name="Chassis Code")),
                ("year_from", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name="Year From")),
                ("year_to", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name="Year To")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("deleted_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Deleted By")),
                ("scope", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dlux.scope", verbose_name="Scope")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Updated By")),
                ("vehicle_model", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="generations", to="automotive.vehiclemodel", verbose_name="Vehicle Model")),
            ],
            options={
                "verbose_name": "Vehicle Generation",
                "verbose_name_plural": "Vehicle Generations",
                "ordering": ["vehicle_model__make__name", "vehicle_model__name", "year_from", "name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleEngine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Deleted At")),
                ("engine_code", models.CharField(blank=True, max_length=80, verbose_name="Engine Code")),
                ("display_name", models.CharField(max_length=120, verbose_name="Engine")),
                ("displacement", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Displacement (L)")),
                ("fuel_type", models.CharField(blank=True, choices=[("gasoline", "Gasoline"), ("diesel", "Diesel"), ("hybrid", "Hybrid"), ("electric", "Electric"), ("lpg", "LPG"), ("other", "Other")], max_length=16, verbose_name="Fuel Type")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("deleted_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Deleted By")),
                ("scope", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dlux.scope", verbose_name="Scope")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Updated By")),
                ("generation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="engines", to="automotive.vehiclegeneration", verbose_name="Generation")),
                ("vehicle_model", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="engines", to="automotive.vehiclemodel", verbose_name="Vehicle Model")),
            ],
            options={
                "verbose_name": "Vehicle Engine",
                "verbose_name_plural": "Vehicle Engines",
                "ordering": ["vehicle_model__make__name", "vehicle_model__name", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleTrim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Deleted At")),
                ("name", models.CharField(max_length=120, verbose_name="Trim")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("deleted_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Deleted By")),
                ("generation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="trims", to="automotive.vehiclegeneration", verbose_name="Generation")),
                ("scope", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dlux.scope", verbose_name="Scope")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Updated By")),
                ("vehicle_model", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="trims", to="automotive.vehiclemodel", verbose_name="Vehicle Model")),
            ],
            options={
                "verbose_name": "Vehicle Trim",
                "verbose_name_plural": "Vehicle Trims",
                "ordering": ["vehicle_model__make__name", "vehicle_model__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductFitment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Deleted At")),
                ("year_from", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name="Year From")),
                ("year_to", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name="Year To")),
                ("transmission", models.CharField(blank=True, choices=[("automatic", "Automatic"), ("manual", "Manual"), ("cvt", "CVT"), ("dct", "DCT"), ("other", "Other")], max_length=16, verbose_name="Transmission")),
                ("position", models.CharField(blank=True, choices=[("front", "Front"), ("rear", "Rear"), ("front_left", "Front Left"), ("front_right", "Front Right"), ("rear_left", "Rear Left"), ("rear_right", "Rear Right")], max_length=20, verbose_name="Position")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("deleted_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Deleted By")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="automotive_fitments", to="catalog.product", verbose_name="Product")),
                ("scope", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dlux.scope", verbose_name="Scope")),
                ("updated_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Updated By")),
                ("engine", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="product_fitments", to="automotive.vehicleengine", verbose_name="Engine")),
                ("generation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="product_fitments", to="automotive.vehiclegeneration", verbose_name="Generation")),
                ("vehicle_model", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="product_fitments", to="automotive.vehiclemodel", verbose_name="Vehicle Model")),
                ("trim", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="product_fitments", to="automotive.vehicletrim", verbose_name="Trim")),
            ],
            options={
                "verbose_name": "Product Fitment",
                "verbose_name_plural": "Product Fitments",
                "ordering": ["product__name", "vehicle_model__make__name", "vehicle_model__name", "year_from"],
            },
        ),
        migrations.AddConstraint(
            model_name="vehiclemake",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("name"), models.F("scope_id"), condition=models.Q(("deleted_at__isnull", True), ("scope__isnull", False)), name="auto_make_name_scope_ci"),
        ),
        migrations.AddConstraint(
            model_name="vehiclemake",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("name"), condition=models.Q(("deleted_at__isnull", True), ("scope__isnull", True)), name="auto_make_name_global_ci"),
        ),
        migrations.AddConstraint(
            model_name="vehiclemodel",
            constraint=models.UniqueConstraint(models.F("make_id"), django.db.models.functions.text.Lower("name"), condition=models.Q(("deleted_at__isnull", True)), name="auto_model_make_name_ci"),
        ),
        migrations.AddConstraint(
            model_name="vehiclegeneration",
            constraint=models.CheckConstraint(condition=models.Q(("year_from__lte", models.F("year_to"))), name="auto_gen_year_order"),
        ),
        migrations.AddConstraint(
            model_name="vehiclegeneration",
            constraint=models.UniqueConstraint(models.F("vehicle_model_id"), django.db.models.functions.text.Lower("name"), models.F("year_from"), models.F("year_to"), condition=models.Q(("deleted_at__isnull", True)), name="auto_gen_model_name_years"),
        ),
        migrations.AddConstraint(
            model_name="vehicleengine",
            constraint=models.UniqueConstraint(models.F("vehicle_model_id"), django.db.models.functions.comparison.Coalesce("generation_id", models.Value(0)), django.db.models.functions.text.Lower("engine_code"), django.db.models.functions.text.Lower("display_name"), condition=models.Q(("deleted_at__isnull", True)), name="auto_engine_identity_uniq"),
        ),
        migrations.AddConstraint(
            model_name="vehicletrim",
            constraint=models.UniqueConstraint(models.F("vehicle_model_id"), django.db.models.functions.comparison.Coalesce("generation_id", models.Value(0)), django.db.models.functions.text.Lower("name"), condition=models.Q(("deleted_at__isnull", True)), name="auto_trim_identity_uniq"),
        ),
        migrations.AddIndex(
            model_name="productfitment",
            index=models.Index(fields=["product"], name="auto_fitment_product_idx"),
        ),
        migrations.AddIndex(
            model_name="productfitment",
            index=models.Index(fields=["vehicle_model", "year_from", "year_to"], name="auto_fitment_vehicle_idx"),
        ),
        migrations.AddConstraint(
            model_name="productfitment",
            constraint=models.CheckConstraint(condition=models.Q(("year_from__lte", models.F("year_to"))), name="auto_fitment_year_order"),
        ),
        migrations.AddConstraint(
            model_name="productfitment",
            constraint=models.UniqueConstraint(models.F("product_id"), models.F("vehicle_model_id"), models.F("year_from"), models.F("year_to"), django.db.models.functions.comparison.Coalesce("generation_id", models.Value(0)), django.db.models.functions.comparison.Coalesce("engine_id", models.Value(0)), django.db.models.functions.comparison.Coalesce("trim_id", models.Value(0)), models.F("transmission"), models.F("position"), condition=models.Q(("deleted_at__isnull", True)), name="auto_fitment_identity_uniq"),
        ),
    ]
