# Generated by Django 6.0.8 on 2026-09-28 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0001_initial'),
        ('catalog', '0007_product_service_image_assets'),
        ('dlux', '0023_ops_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('part_brand', models.CharField(blank=True, max_length=120, verbose_name='Part Brand')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part_profile', to='catalog.product', verbose_name='Product')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Part Profile',
                'verbose_name_plural': 'Part Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProductPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('kind', models.CharField(choices=[('oem', 'OEM'), ('cross', 'Cross-reference')], max_length=8, verbose_name='Type')),
                ('number', models.CharField(max_length=80, verbose_name='Part Number')),
                ('normalized', models.CharField(db_index=True, editable=False, max_length=80)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_numbers', to='catalog.product', verbose_name='Product')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Part Number',
                'verbose_name_plural': 'Part Numbers',
                'ordering': ['product__name', 'kind', 'number'],
                'constraints': [models.UniqueConstraint(models.F('product_id'), models.F('kind'), models.F('normalized'), condition=models.Q(('deleted_at__isnull', True)), name='auto_part_number_uniq')],
            },
        ),
    ]
