# Generated by Django 6.0.8 on 2026-09-28 18:47

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0002_part_profile_and_numbers'),
        ('catalog', '0007_product_service_image_assets'),
        ('dlux', '0023_ops_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='productfitment',
            name='auto_fitment_year_order',
        ),
        migrations.RemoveConstraint(
            model_name='productfitment',
            name='auto_fitment_identity_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='vehicleengine',
            name='auto_engine_identity_uniq',
        ),
        migrations.AddField(
            model_name='vehicleengine',
            name='fitted_models',
            field=models.ManyToManyField(blank=True, related_name='shared_engines', to='automotive.vehiclemodel', verbose_name='Fitted Models'),
        ),
        migrations.AddField(
            model_name='vehicleengine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=120, verbose_name='Engine Manufacturer'),
        ),
        migrations.AlterField(
            model_name='productfitment',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_fitments', to='automotive.vehiclemodel', verbose_name='Vehicle Model'),
        ),
        migrations.AlterField(
            model_name='productfitment',
            name='year_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Year From'),
        ),
        migrations.AlterField(
            model_name='productfitment',
            name='year_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Year To'),
        ),
        migrations.AlterField(
            model_name='vehicleengine',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='automotive.vehiclemodel', verbose_name='Vehicle Model'),
        ),
        migrations.AddConstraint(
            model_name='productfitment',
            constraint=models.CheckConstraint(condition=models.Q(('year_from__isnull', True), ('year_to__isnull', True), ('year_from__lte', models.F('year_to')), _connector='OR'), name='auto_fitment_year_order'),
        ),
        migrations.AddConstraint(
            model_name='productfitment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('year_from__isnull', True), ('year_to__isnull', True)), models.Q(('year_from__isnull', False), ('year_to__isnull', False)), _connector='OR'), name='auto_fitment_years_paired'),
        ),
        migrations.AddConstraint(
            model_name='productfitment',
            constraint=models.CheckConstraint(condition=models.Q(('vehicle_model__isnull', False), ('engine__isnull', False), _connector='OR'), name='auto_fitment_has_target'),
        ),
        migrations.AddConstraint(
            model_name='productfitment',
            constraint=models.UniqueConstraint(models.F('product_id'), django.db.models.functions.comparison.Coalesce('vehicle_model_id', models.Value(0)), django.db.models.functions.comparison.Coalesce('year_from', models.Value(0)), django.db.models.functions.comparison.Coalesce('year_to', models.Value(0)), django.db.models.functions.comparison.Coalesce('generation_id', models.Value(0)), django.db.models.functions.comparison.Coalesce('engine_id', models.Value(0)), django.db.models.functions.comparison.Coalesce('trim_id', models.Value(0)), models.F('transmission'), models.F('position'), condition=models.Q(('deleted_at__isnull', True)), name='auto_fitment_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vehicleengine',
            constraint=models.UniqueConstraint(models.F('vehicle_model_id'), django.db.models.functions.comparison.Coalesce('generation_id', models.Value(0)), django.db.models.functions.text.Lower('engine_code'), django.db.models.functions.text.Lower('display_name'), condition=models.Q(('deleted_at__isnull', True), ('vehicle_model__isnull', False)), name='auto_engine_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vehicleengine',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('manufacturer'), django.db.models.functions.text.Lower('engine_code'), django.db.models.functions.text.Lower('display_name'), condition=models.Q(('deleted_at__isnull', True), ('vehicle_model__isnull', True)), name='auto_shared_engine_uniq'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_models', to='automotive.equipmenttype', verbose_name='Equipment Type'),
        ),
        migrations.AddConstraint(
            model_name='equipmenttype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='auto_equipment_type_name_ci'),
        ),
    ]
