# Generated by Django 6.0.8 on 2026-10-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0003_heavy_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='alias',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local alias'),
        ),
    ]
