# Generated by Django 6.0.8 on 2026-09-28 21:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0023_ops_run'),
        ('sales', '0007_invoiceitem_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=20, verbose_name='Method'),
        ),
        migrations.CreateModel(
            name='PosSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Idempotency Key')),
                ('till', models.CharField(blank=True, max_length=60, verbose_name='Till')),
                ('tendered_lyd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Cash Tendered (LYD)')),
                ('change_lyd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Change (LYD)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sale', to='sales.invoice', verbose_name='Invoice')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'POS Sale',
                'verbose_name_plural': 'POS Sales',
                'ordering': ['-created_at'],
                'permissions': [('use_pos', 'Can sell from the point-of-sale till'), ('pos_unlimited_discount', 'Can give any discount at the till')],
            },
        ),
    ]
