# Generated by Django 6.0.8 on 2026-10-02 13:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0023_ops_run'),
        ('sales', '0009_invoice_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('action', models.CharField(choices=[('refund', 'Refund'), ('credit', 'Customer credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20)),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_resolutions', to='sales.customer')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resolution', to='sales.payment')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_uses', to='sales.invoice')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='sales.paymentresolution')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='paymentresolution',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sales_resolution_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentresolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'refund'), ('method__in', ['cash', 'card', 'bank_transfer', 'cheque'])), models.Q(('action', 'credit'), ('customer__isnull', False), ('method', '')), _connector='OR'), name='sales_resolution_disposition'),
        ),
        migrations.AddConstraint(
            model_name='customercredituse',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sales_credit_use_positive'),
        ),
    ]
