# Generated by Django 6.0.8 on 2026-10-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_paymentresolution_customercredituse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_cost_lyd',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=18, null=True, verbose_name='Unit Cost (LYD)'),
        ),
    ]
